### ISSUE TITLE
Block-scoped declarations error

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/ion#136]
After installing `ganache-cli` globally I get the following error

```
vagrant@ubuntu-xenial:~/src/ion$ npm run testrpc

> ion-truffle@1.0.0 testrpc /home/vagrant/src/ion
> ganache-cli --port 8545 --gasLimit 0xFFFFFFFFFFF --gasPrice 0 --defaultBalanceEther 99999999999 --networkId 1234

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ganache-cli/cli.js:12:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-141-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "testrpc"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ion-truffle@1.0.0 testrpc: `ganache-cli --port 8545 --gasLimit 0xFFFFFFFFFFF --gasPrice 0 --defaultBalanceEther 99999999999 --networkId 1234`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ion-truffle@1.0.0 testrpc script 'ganache-cli --port 8545 --gasLimit 0xFFFFFFFFFFF --gasPrice 0 --defaultBalanceEther 99999999999 --networkId 1234'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ion-truffle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ganache-cli --port 8545 --gasLimit 0xFFFFFFFFFFF --gasPrice 0 --defaultBalanceEther 99999999999 --networkId 1234
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ion-truffle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ion-truffle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/src/ion/npm-debug.log
```

**Comment by shapeshed** [comment]
This is down to an old version of node on Ubuntu 18.04
Will open another ticket to specify the version of node in the README
