### ISSUE TITLE
Install problem on MacOS

### ISSUE THREAD

**Issue by saronimo** [clearmatics/ion#141]
Running tests fails on MacOS. Install node via homebrew `11.8.0`

```
> ion-truffle@1.0.0 test /Users/sf/Documents/ion
> truffle test

(node:16852) V8: /Users/sf/Documents/ion/node_modules/truffle/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
Compiling ./contracts/EventVerifier.sol...
Compiling ./contracts/Ion.sol...
Compiling ./contracts/IonCompatible.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/functional/Function.sol...
Compiling ./contracts/functional/Trigger.sol...
Compiling ./contracts/functional/TriggerEventVerifier.sol...
Compiling ./contracts/libraries/ECVerify.sol...
Compiling ./contracts/libraries/PatriciaTrie.sol...
Compiling ./contracts/libraries/RLP.sol...
Compiling ./contracts/libraries/SafeMath.sol...
Compiling ./contracts/libraries/SolidityUtils.sol...
Compiling ./contracts/mock/MockIon.sol...
Compiling ./contracts/mock/MockStorage.sol...
Compiling ./contracts/mock/MockValidation.sol...
Compiling ./contracts/storage/BlockStore.sol...
Compiling ./contracts/storage/EthereumStore.sol...
Compiling ./contracts/validation/Clique.sol...
Compiling ./test/PatriciaTrieTest.sol...
Compiling truffle/Assert.sol...

Compilation warnings encountered:

/Users/sf/Documents/ion/contracts/storage/BlockStore.sol:55:5: Warning: Modifiers of functions without implementation are ignored.
    function addBlock(bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob) onlyIon onlyRegisteredChains(_chainId);
    ^---------------------------------------------------------------------------------------------------------------^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:399:17: Warning: The use of labels is deprecated. Please use "if", "switch", "for" or function calls instead.
                tag_loop:
                ^------^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:399:17: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
                tag_loop:
                ^------^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:400:17: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
                jumpi(end, eq(i, words))
                ^----------------------^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:406:17: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
                jump(tag_loop)
                ^------------^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:407:17: Warning: The use of labels is deprecated. Please use "if", "switch", "for" or function calls instead.
                end:
                ^-^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:407:17: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
                end:
                ^-^
,/Users/sf/Documents/ion/contracts/storage/BlockStore.sol:55:5: Warning: No visibility specified. Defaulting to "public". 
    function addBlock(bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob) onlyIon onlyRegisteredChains(_chainId);
    ^---------------------------------------------------------------------------------------------------------------^
,/Users/sf/Documents/ion/contracts/storage/EthereumStore.sol:53:5: Warning: No visibility specified. Defaulting to "public". 
    function addBlock(bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob)
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/storage/EthereumStore.sol:178:5: Warning: No visibility specified. Defaulting to "public". 
    function verifyProof(bytes _value, bytes _parentNodes, bytes _path, bytes32 _hash) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/functional/TriggerEventVerifier.sol:29:9: Warning: Unused local variable.
        bytes memory contractEmittedEvent = RLP.toData(log[0]);
        ^-------------------------------^
,/Users/sf/Documents/ion/contracts/functional/TriggerEventVerifier.sol:30:9: Warning: Unused local variable.
        RLP.RLPItem[] memory topics = RLP.toList(log[1]);
        ^-------------------------^
,/Users/sf/Documents/ion/contracts/mock/MockIon.sol:8:5: Warning: No visibility specified. Defaulting to "public". 
    constructor(bytes32 _id) Ion(_id) {}
    ^----------------------------------^
,/Users/sf/Documents/ion/contracts/mock/MockIon.sol:18:5: Warning: No visibility specified. Defaulting to "public". 
    function addChain(address _storageAddress, bytes32 _chainId) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/mock/MockStorage.sol:22:5: Warning: No visibility specified. Defaulting to "public". 
    function addBlock(bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/mock/MockStorage.sol:22:23: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function addBlock(bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob) {
                      ^--------------^
,/Users/sf/Documents/ion/contracts/mock/MockStorage.sol:22:61: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function addBlock(bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob) {
                                                            ^--------------^
,/Users/sf/Documents/ion/contracts/mock/MockValidation.sol:13:5: Warning: No visibility specified. Defaulting to "public". 
    function SubmitBlock(address _storageAddress, bytes32 _chainId, bytes32 _blockHash, bytes _blockBlob) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/validation/Clique.sol:155:98: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function addGenesisBlock(bytes32 _chainId, address[] _validators, bytes32 _genesisBlockHash, address _storeAddr) internal {
                                                                                                 ^----------------^
,/Users/sf/Documents/ion/contracts/validation/Clique.sol:326:5: Warning: No visibility specified. Defaulting to "public". 
    function getValidators(bytes32 _chainId, bytes32 _blockHash) constant returns (address[]) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/validation/Clique.sol:330:5: Warning: No visibility specified. Defaulting to "public". 
    function getProposal(bytes32 _chainId, bytes32 _blockHash, address _candidate) constant returns (uint256) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/test/PatriciaTrieTest.sol:9:5: Warning: No visibility specified. Defaulting to "public". 
    function testSucceedVerifyNestedNodes() returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/test/PatriciaTrieTest.sol:43:5: Warning: No visibility specified. Defaulting to "public". 
    function testFailVerifyNestedNodes() returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/Ion.sol:42:5: Warning: Function state mutability can be restricted to view
    function isContract(address _addr) internal returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/libraries/PatriciaTrie.sol:114:5: Warning: Function state mutability can be restricted to pure
    function checkNodeValue(bytes _expected, bytes _nodeValue) private returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:171:5: Warning: Function state mutability can be restricted to view
    function toBytes(RLPItem memory self) internal returns (bytes memory bts) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:183:5: Warning: Function state mutability can be restricted to view
    function toData(RLPItem memory self) internal returns (bytes memory bts) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:214:5: Warning: Function state mutability can be restricted to view
    function toAscii(RLPItem memory self) internal returns (string memory str) {
    ^ (Relevant source part starts here and spans across multiple lines).
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:400:17: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
                jumpi(end, eq(i, words))
                ^----------------------^
,/Users/sf/Documents/ion/contracts/libraries/RLP.sol:406:17: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
                jump(tag_loop)
                ^------------^
,/Users/sf/Documents/ion/contracts/validation/Clique.sol:185:5: Warning: Function state mutability can be restricted to view
    function checkSignature(bytes32 _chainId, bytes _extraData, bytes _rlpBlockHeader, bytes32 _parentBlockHash) internal returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).

Error: The module '/Users/sf/Documents/ion/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:777:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sf/Documents/ion/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sf/Documents/ion/node_modules/scrypt.js/node.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sf/Documents/ion/node_modules/web3/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:29:32)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sf/Documents/ion/node_modules/web3/node_modules/web3-eth/dist/web3-eth.cjs.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion-truffle@1.0.0 test: `truffle test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ion-truffle@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sf/.npm/_logs/2019-01-29T17_51_37_250Z-debug.log
```

**Comment by shapeshed** [comment]
This was fixed by hosing the `./node_modules` directory and reinstalling. Was a local issue.
