### ISSUE TITLE
Ganache race condition bug, needs workaround

### ISSUE THREAD

**Issue by HarryR** [clearmatics/ion#80]
I ran into a weird bug with Ganache-cli

There are two sides which connect to Ganache via EthRPC, they each use a persistent HTTP connection via `requests.Session`. Lets call them client A and client B.

 * Client A submits a transaction that modifies a contract.
 * Client A asks for a receipt for the transaction, it gets it
 * Client B provides the transaction ID to client A
 * Client B verifies, using `call`, that the contract has been modified.
 * Client B is unable to get a receipt for the transaction ID that Client A gave it.

This was discovered due to another bug in Ganache-cli where Client B wasn't seeing the some of the modifications that Client A had made. e.g. after being notified of the 'release' step it checked the contract but the state was still 'Deposited' and not 'Withdrawn'. So I tried to pull the transaction receipt, or wait until it came through - but it never did. After the next call (in 'finish' step) client B would see the changes to the contract from both the 'release' and 'finish' steps, but still can't retrieve any of the transactions.

Going to try some workarounds, but this is pretty annoying. The transaction debugger also barfs on the transactions, which is even more annoying, there is weirdness in Ganache.

This is with the latest (at time of writing) release of Ganache: 6.1.3.

I've tried two things which didn't seem to make any difference:

 * Closing connection after each request
 * Prefixing transaction ID with '0x', rather than just being unprefixed hex as ascii

When trying to debug the transaction with truffle, it craps out a big stacktrace, which indicates it's getting a null transaction too, but if I change the transaction ID it tells me 'unknown transaction' - so it's definitely a bug with Ganache...

This bug has been found by others:

 * https://gitcoin.co/universe/4422/typeerror-cannot-read-property-context-of-null
 * https://github.com/trufflesuite/truffle-debugger/issues/39

```
redux-saga error: uncaught at session.saga
at session.saga 
 at recordInstance 
 TypeError: Cannot read property 'context' of null
    at Object.addInstance$ (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/truffle-debugger/dist/debugger.js:5533:1)
    at tryCatch (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:62:15)
    at Generator.invoke [as _invoke] (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:296:1)
    at Generator.prototype.(anonymous function) [as next] (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:114:1)
    at tryCatch (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:62:15)
    at maybeInvokeDelegate (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:358:1)
    at Generator.invoke [as _invoke] (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:270:1)
    at Generator.prototype.(anonymous function) [as next] (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:114:1)
    at next (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:311:1)
    at currCb (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
    at runSelectEffect (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
    at runEffect (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
    at next (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
    at proc (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:270:1)
    at resolveIterator (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:456:1)
    at runCallEffect (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:517:1)
    at runEffect (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
    at /home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:644:1
    at Array.forEach (<anonymous>)
    at runAllEffect (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:643:1)
    at runEffect (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
    at next (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
    at currCb (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
    at checkEffectEnd (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:612:1)
    at chCbAtKey (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:627:1)
    at Object.currCb [as cb] (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
    at /home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:358:1
    at Array.forEach (<anonymous>)
    at end (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:357:1)
    at Object.task.cont (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:99:1)
    at next (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:321:1)
    at currCb (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
    at takeCb (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:466:1)
    at Object.put (/home/user/github.com/HarryR/ion/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:73:1)
```

**Comment by HarryR** [comment]
Ah nevermind, it was because the transaction id wasn't prefixed with '0x'
